/** @format */
import localFont from 'next/font/local';
import './globals.css';
import Navbar from './components/navbar/navbar';
import AnimatedCursor from 'react-animated-cursor';
import { SmoothScrollProvider } from './components/animations/smoothscrollwrapper';
import Footer from './components/footer';
import Preloader from './preloader';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SmoothScrollProvider>
          <Navbar />
          <AnimatedCursor
            innerSize={8}
            outerSize={35}
            innerScale={1}
            outerScale={2}
            outerAlpha={0}
            hasBlendMode={true}
            innerStyle={{
              backgroundColor: '#ffde16',
            }}
            outerStyle={{
              border: '3px solid #ffde16',
            }}
          />{' '}
          {children}
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
