name: Build and Deploy Next.js Site

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch (can change if using another branch)
  workflow_dispatch:  # This allows manual triggering from GitHub UI
  # Add a trigger for WordPress webhook (optional, if you want to trigger on new post)
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0 '  # You can adjust the version based on your Next.js needs

    - name: Install dependencies
      run: |
        npm install

    - name: Build Next.js site
      run: |
        npm run build
        # npm run export  # This generates static files in the 'out' directory

    - name: Upload Static Files to Hosting via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 82.112.232.1
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out  # This is the directory where your static files are generated
        remote-dir: /public_html  # The directory on your shared hosting server
